apiVersion: v1
kind: Service
metadata:
  name: patient-data
  namespace: hospital-space
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: hospital
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
  namespace: hospital-space
  labels:
    app: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
        - name: hospital-app
          image: hospital-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
