apiVersion: apps/v1
kind: Deployment
metadata:
  name: pharma
  namespace: pharma-space
  labels:
    app: pharma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pharma
  template:
    metadata:
      labels:
        app: pharma
    spec:
      containers:
        - name: pharma-app
          image: pharma-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
