apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: app-ns
  labels:
    run: app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: app
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: app
          image: app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
