apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: app-space
spec:
  containers:
    - name: app
      image: lucafrancescato/app:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
