apiVersion: v1
kind: Namespace
metadata:
  name: app-ns
  labels:
    data-space/apply-netpol: "true"
    data-space/apply-reconcile: "true"
    data-space/apply-webhook: "true"
    data-space/netpol-allow: "true"
