apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app-space
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
