apiVersion: v1
kind: Service
metadata:
  name: dst-svc
  namespace: dst-ns
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: webserver
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: dst-ns
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: webserver:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
