apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: data-spacer-manager-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: data-spacer-manager-clusterrole
subjects:
  - kind: ServiceAccount
    name: service-account
    namespace: data-spacer
