apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: data-spacer-manager-clusterrole
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["namespaces/finalizers"]
    verbs: ["update"]

  - apiGroups: [""]
    resources: ["namespaces/status"]
    verbs: ["get", "patch", "update"]

  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  - apiGroups: [""]
    resources: ["pods/finalizers"]
    verbs: ["update"]

  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "patch", "update"]
