apiVersion: v1
kind: Service
metadata:
  name: manager-webhook-svc
  namespace: data-spacer
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  ports:
    - name: https
      port: 9443
      targetPort: webhook
